### ISSUE TITLE
would be helpful for overview script to know paths to all the output files

### ISSUE THREAD

**Issue by sknorr** [openSUSE/docserv#16] opened 2018-11-09 16:13 UTC
the overview script needs to generate links from the overview page to all the html index/pdf/epub files. it is possible to guess (and it works sort of kind of maybe probably usually okayish for portwinestain), but it would be great if we had proper information on where all the output files went. Also see #7.

**Comment by svenseeberg** [comment] 2018-11-12 17:12
Almost duplicate of #18

**Closed** 2018-11-13 11:21 UTC

**Comment by sknorr** [comment] 2018-11-21 14:42
Drats, you right.
